### ISSUE TITLE
typo at line 559

### ISSUE THREAD

**Issue by SteveMacSteve** [sherzodr/penmon#2]
`        return round((0.75 + (210 ** (-5)) * self.station.altitude) * self.R_a(), 1)` 
should be:
`        return round((0.75 + (2 * 10 ** (-5)) * self.station.altitude) * self.R_a(), 1)`

Correct?

**Comment by sherzodr** [comment]
Hi Steve,

You know what, you are absolutely right! My mistake! Thanks for pointing it out. 

Instead of convoluted `2 * 10 ** (-5)`  rewriting it as  `2 / 100000` would give the same result, and easier on the eye too! I will try to fix it tonight. 

Thanks again!

**Comment by sherzodr** [comment]
Fixed.

**Comment by SteveMacSteve** [comment]
Ciao Thank you for the library! stefano
At 16 Feb 2022 19:48:17 +0100 (CET) from sherzodr ***@***.***>:
 
Hi Steve,
You know what, you are absolutely right! My mistake! Thanks for pointing it out.
Instead of convoluted 2 * 10 ** (-5) rewriting it as 2 / 100000 would give the same result, and easier on the eye too! I will try to fix it tonight.
Thanks again!
